### ISSUE TITLE
Todo/Fazer

### ISSUE THREAD

**Issue by LucasADCT** [LucasADCT/flappy-bird#1]
**Criar a estrutura inicial do jogo:**
- [ ] Setup inicial do canvas
- [ ] Desenhar o Flappy Bird na tela
- [ ] Game loop
- [ ] Desenhar o resto do cenário
- [ ] Adicionar tela de início
**Organizando projetos:**
